import {
  Baby,
  BadgeDollarSign,
  Banknote,
  Book,
  Briefcase,
  Building2,
  Bus,
  Car,
  Coffee,
  Coins,
  CreditCard,
  Dog,
  DollarSign,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  Music,
  MoreHorizontal,
  PiggyBank,
  Plane,
  Receipt,
  Repeat,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Stethoscope,
  TrendingUp,
  Users,
  Utensils,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Category `icon` values are plain strings stored in SQLite (docs/database/SCHEMA.md).
 * This is the closed set the category icon picker offers — keep it in sync with
 * both the seed data in src-tauri/migrations/001_init.sql and the picker UI.
 */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  'shopping-cart': ShoppingCart,
  home: Home,
  zap: Zap,
  car: Car,
  smartphone: Smartphone,
  repeat: Repeat,
  users: Users,
  briefcase: Briefcase,
  'building-2': Building2,
  'heart-pulse': HeartPulse,
  utensils: Utensils,
  'shopping-bag': ShoppingBag,
  film: Film,
  'more-horizontal': MoreHorizontal,
  wallet: Wallet,
  'trending-up': TrendingUp,
  laptop: Laptop,
  // Money / finance
  'dollar-sign': DollarSign,
  banknote: Banknote,
  coins: Coins,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  'hand-coins': HandCoins,
  'badge-dollar-sign': BadgeDollarSign,
  receipt: Receipt,
  // Lifestyle / other categories
  plane: Plane,
  bus: Bus,
  fuel: Fuel,
  'graduation-cap': GraduationCap,
  gamepad: Gamepad2,
  coffee: Coffee,
  dumbbell: Dumbbell,
  stethoscope: Stethoscope,
  music: Music,
  baby: Baby,
  dog: Dog,
  'shopping-basket': ShoppingBasket,
  store: Store,
  book: Book,
  gift: Gift,
  sparkles: Sparkles,
  wrench: Wrench,
}

export function getCategoryIcon(icon: string): LucideIcon {
  return CATEGORY_ICONS[icon] ?? MoreHorizontal
}
